package com.mishin.core.domain.model

/**
 * An alert generated by the system (e.g., low stock).
 */
data class Alert(
    val id: String,
    val locationId: String,
    val type: AlertType,
    val inventoryItemId: String?,
    val message: String,
    val isRead: Boolean,
    val createdAt: String,
    val syncedAt: String?
)

enum class AlertType {
    LOW_STOCK,
    OUT_OF_STOCK,
    RESERVATION_REMINDER,
    SYSTEM
}
